apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-ingressgateway
spec:
  selector:
    istio: ingressgateway
  servers:
   - port:
       number: 443
       protocol: HTTPS
       name: https
     tls:
       mode: SIMPLE
       credentialName: exampleboutique-credential
     hosts:
     - "*"

#---
#apiVersion: networking.istio.io/v1alpha3
#kind: Gateway
#metadata:
#  name: cross-network-gateway
#spec:
#  selector:
#    istio: ingressgateway
#  servers:
#  - port:
#      number: 443
#      name: tls
#      protocol: TLS
#    tls:
#      mode: AUTO_PASSTHROUGH
#    hosts:
#    - "*.local"
