kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny-all
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress

---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: frontend-allow-ingress-external
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
  - Ingress
  ingress:
  - from: []

---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: frontend-allow-egress-store-and-lb
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: store-in-scope
    - ipBlock:
        cidr: 21.0.204.245/32

#  - to: []
#    - podSelector: {}

#---
#kind: NetworkPolicy
#apiVersion: networking.k8s.io/v1
#metadata:
#  name: deny-from-other-namespaces
#spec:
#  podSelector: {}
#  policyTypes:
#  - Ingress
#  - Egress
#  ingress:
#  - from:
#    - podSelector: {}
#  egress:
#  - to:
#    - podSelector: {}
#    - ipBlock:
#        cidr: 21.0.204.245/32
#    - namespaceSelector:
#        matchLabels:
#          name: store-out-of-scope

#  - to: []
#    - podSelector: {}

