apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-ingress
spec:
  hosts:
  - "*"
  gateways:
  - frontend/istio-ingressgateway
  http:
  - route:
    - destination:
        host: frontend.frontend.svc.cluster.local
        port:
          number: 80
