apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
   - port:
       number: 443
       protocol: HTTPS
       name: https
     tls:
       mode: SIMPLE
       credentialName: exampleboutique-credential
     hosts:
     - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-ingress
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/istio-ingressgateway
  http:
  - route:
    - destination:
        host: frontend.store-in-scope.svc.cluster.local
        port:
          number: 80