apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: istio-reader-service-account
  namespace: istio-system

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: istio-reader-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-reader-role
subjects:
- kind: ServiceAccount
  name: istio-reader-service-account
  namespace: istio-system
