apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-ingress
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/istio-ingressgateway
  http:
  - route:
    - destination:
#        host: frontend.store-in-scope.svc.cluster.local
        host: nginx.store-in-scope.svc.cluster.local
        port:
          number: 80
