kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: deny-from-other-namespaces
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}
  # allow all egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: store-out-of-scope

#  - to: []
#    - podSelector: {}

#---
#kind: NetworkPolicy
#apiVersion: networking.k8s.io/v1
#metadata:
#  name: allow-egress-to-out-of-scope
#spec:
#  podSelector:
#    matchLabels:
#      app: frontend
#  policyTypes:
#  - Egress
#  egress:
#  - to: []

#    - namespaceSelector:
#        matchLabels:
#          name: store-out-of-scope

#---
#kind: NetworkPolicy
#apiVersion: networking.k8s.io/v1
#metadata:
#  name: frontend-allow-external
#spec:
#  podSelector:
#    matchLabels:
#      app: frontend
#  policyTypes:
#  - Ingress
#  ingress:
#  - from: []
###    ports:
###    - port: 8080
