kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: deny-from-other-namespaces
spec:
  podSelector: {}
#    matchLabels:
  policyTypes:
    - Ingress
#  ingress:
#  - from:
#    - podSelector: {}
#
#---
#kind: NetworkPolicy
#apiVersion: networking.k8s.io/v1
#metadata:
#  name: frontend-allow-external
#spec:
#  podSelector:
#    matchLabels:
#      app: frontend
#  ingress:
#  - ports:
#    - port: 8080
#    from: []
